version: '2.2'
services:
  elasticsearch-server:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.10
    container_name: elasticsearch-server
    hostname: elasticsearch-server
    environment:
      # - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /home/harold/elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - dockernet
  #elasticsearch2:
  #  image: docker.elastic.co/elasticsearch/elasticsearch:6.8.10
  #  container_name: elasticsearch-server2
  #  hostname: elasticsearch-server2
  #  environment:
  #    - cluster.name=docker-cluster
  #    - bootstrap.memory_lock=true
  #    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #    - "discovery.zen.ping.unicast.hosts=elasticsearch"
  #  ulimits:
  #    memlock:
  #      soft: -1
  #      hard: -1
  #  volumes:
  #    - esdata2:/usr/share/elasticsearch/data
  #  networks:
  #    - dockernet
  kibana-server:
    image: docker.elastic.co/kibana/kibana:6.8.10
    container_name: kibana-server
    hostname: kibana-server
    environment:
      SERVER_NAME: kibana-server
      ELASTICSEARCH_HOSTS: http://elasticsearch-server
    # volumes:
    #   - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - dockernet

networks:
  dockernet:
    external: true

